services:
  # 1. Base de Datos
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: chanataxi_leccion2_db
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306" # Puerto externo 3307 para no chocar con tu MySQL local
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 10s
      retries: 5

  # 2. Backend (Java)
  api:
    build: ./Chanataxi_Leccion2
    ports:
      - "8080:8080"
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: chanataxi_leccion2_db
      DB_USER: user
      DB_PASSWORD: password
    depends_on:
      db:
        condition: service_healthy

  # 3. Frontend (React/Nginx)
  web:
    build: ./frontend-chanataxi
    ports:
      - "5173:80" # Entras por localhost:5173
    depends_on:
      - api

volumes:
  db_data: